### ISSUE TITLE
migrateRouterVM fails due to storagepool tags

### ISSUE THREAD

**Issue by remibergsma** [schubergphilis/cloudstackOps#24]
`./migrateRouterVM.py -c beta-nl2_admin -r r-924-VM -t mccxpod01-cs03 -s mccxpod00-core-db01.app.mccxpod00.sbp.mccx-nl2`

```
Error: Execute cmd: liststoragepools failed, due to: errorCode: 431, errorText:Unable to execute API command liststoragepools due to invalid value. Invalid parameter id value=[{podname : u'mccxpod01', storagecapabilities : {VOLUME_SNAPSHOT_QUIESCEVM : u'false'}, name : u'BETA_NL2_MCCXPOD01_CS03', disksizeallocated : 12582921216, podid : u'904e4341-2415-408a-a13c-cde64cade412', clustername : u'mccxpod01-cs03', ipaddress : u'mccxpod01-nas-x1.storage.mccxpod01.sbp.mccx-nl2.mcinfra.net', created : u'2015-12-28T12:59:37+0100', clusterid : u'608c9d44-9de5-45d4-971f-01b6543133c4', zoneid : u'aa4493c5-d73f-48be-ba3c-7b6f0549bac1', state : u'Up', disksizeused : 3698589696, id : u'317f59d3-b76f-3841-97d3-2f5c084570ed', overprovisionfactor : u'2.0', path : u'/BETA_NL2_MCCXPOD01_CS03', zonename : u'BETA-NL2', type : u'NetworkFilesystem', scope : u'CLUSTER', disksizetotal : 1099511627776}] due to incorrect long value format, or entity does not exist or due to incorrect parameter annotation for the field in api cmd class.
Traceback (most recent call last):
  File "./migrateRouterVM.py", line 274, in <module>
    if c.checkZone(routerClusterID, toClusterID) > 0:
  File "/home/fborn/git/cloudstackOps/cloudstackops/cloudstackops.py", line 1072, in checkZone
    storagepooltags = self.getStoragePoolTags(toClusterID)
  File "/home/fborn/git/cloudstackOps/cloudstackops/cloudstackops.py", line 1031, in getStoragePoolTags
    return targetStoragePoolData[0].tags
TypeError: 'int' object is unsubscriptable
```

Via @fborn

**Comment by remibergsma** [comment]
See if it occurs in more scripts:
```
```
