### ISSUE TITLE
UnicodeEncodingError on sending emails

### ISSUE THREAD

**Issue by sanderv32** [schubergphilis/cloudstackOps#46]
Sending emails with improper encoding causes a UnicodeEncodeError:

```
Traceback (most recent call last):
  File "./migrateVirtualMachine.py", line 421, in <module>
    emailbody)
  File "/home/averhaar/cloudstackOps/cloudstackops/cloudstackops.py", line 648, in sendMail
    htmlpart = MIMEText(htmlcontent, 'html')
  File "/usr/lib64/python2.6/email/mime/text.py", line 30, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib64/python2.6/email/message.py", line 224, in set_payload
    self.set_charset(charset)
  File "/usr/lib64/python2.6/email/message.py", line 260, in set_charset
    self._payload = self._payload.encode(charset.output_charset)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 14: ordinal not in range(128)
```

**Comment by sanderv32** [comment]
This issue is fixed by PR #47
